# -*- coding: utf-8 -*-
"""Kaggle Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkSu9046VokhsFy4KU9N5kdHdzfqYUCA

Install
"""

!pip install -q transformers peft accelerate bitsandbytes datasets trl lxml cairosvg

"""Extract the data zip file and read"""

import os
import re
import zipfile
import random
import numpy as np
import pandas as pd
import torch

from lxml import etree
import cairosvg

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)
from trl import SFTTrainer

zip_path = "/content/dl-spring-2026-svg-generation.zip"
extract_dir = "/content/svg_competition_data"

os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_dir)

print(os.listdir(extract_dir))

train_df = pd.read_csv("/content/svg_competition_data/train.csv")
test_df = pd.read_csv("/content/svg_competition_data/test.csv")
sample_sub_df = pd.read_csv("/content/svg_competition_data/sample_submission.csv")

print("train shape:", train_df.shape)
print("test shape:", test_df.shape)
print("sample submission shape:", sample_sub_df.shape)

print("train columns:", train_df.columns.tolist())
print("test columns:", test_df.columns.tolist())
print("sample submission columns:", sample_sub_df.columns.tolist())

display(train_df.head())
display(test_df.head())
display(sample_sub_df.head())

"""Random seed"""

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

"""SVG wash"""

ALLOWED_TAGS = {
    "svg", "g", "path", "rect", "circle", "ellipse",
    "line", "polyline", "polygon",
    "defs", "use", "symbol", "clipPath"
}

MAX_SVG_LEN = 8000
MAX_PATHS = 256

def strip_code_fences(text: str) -> str:
    text = str(text).strip()
    text = re.sub(r"^```(?:xml|svg)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)
    return text.strip()

def normalize_quotes(text: str) -> str:
    return text.replace("’", "'").replace("“", '"').replace("”", '"')

def remove_special_tokens(text: str) -> str:
    text = str(text)
    text = text.replace("<|im_end|>", "")
    text = text.replace("<|im_start|>", "")
    text = text.replace("<|endoftext|>", "")
    text = re.sub(r"<\|fim_prefix\|>", "", text)
    text = re.sub(r"<\|fim_middle\|>", "", text)
    text = re.sub(r"<\|fim_suffix\|>", "", text)
    text = re.sub(r"<\|.*?\|>", "", text)
    return text.strip()

def clean_svg(svg_text: str) -> str:
    svg_text = strip_code_fences(normalize_quotes(svg_text))
    svg_text = remove_special_tokens(svg_text)
    return svg_text.strip()

def local_name(tag):
    if not isinstance(tag, str):
        return None
    if "}" in tag:
        return tag.split("}", 1)[1]
    return tag

def validate_svg(svg_text: str):
    result = {
        "valid": True,
        "reason": "ok",
        "length": len(svg_text),
        "path_count": 0,
    }

    svg_text = clean_svg(svg_text)

    if not svg_text.startswith("<svg"):
        result["valid"] = False
        result["reason"] = "not_start_with_svg"
        return result

    if len(svg_text) > MAX_SVG_LEN:
        result["valid"] = False
        result["reason"] = "too_long"
        return result

    try:
        root = etree.fromstring(svg_text.encode("utf-8"))
    except Exception as e:
        result["valid"] = False
        result["reason"] = f"xml_error: {e}"
        return result

    root_tag = local_name(root.tag)
    if root_tag != "svg":
        result["valid"] = False
        result["reason"] = "root_not_svg"
        return result

    path_count = 0

    for elem in root.iter():
        tag = local_name(elem.tag)

        if tag is None:
            continue

        if tag not in ALLOWED_TAGS:
            result["valid"] = False
            result["reason"] = f"disallowed_tag:{tag}"
            return result

        for attr in elem.attrib:
            attr_name = local_name(attr)
            if attr_name is not None and attr_name.lower().startswith("on"):
                result["valid"] = False
                result["reason"] = f"event_handler:{attr_name}"
                return result

        if tag == "path":
            path_count += 1

    result["path_count"] = path_count

    if path_count > MAX_PATHS:
        result["valid"] = False
        result["reason"] = "too_many_paths"
        return result

    return result

def renderable_svg(svg_text: str):
    try:
        _ = cairosvg.svg2png(
            bytestring=svg_text.encode("utf-8"),
            output_width=256,
            output_height=256
        )
        return True, "ok"
    except Exception as e:
        return False, str(e)

"""Rewash SVG"""

train_df["svg_clean"] = train_df["svg"].astype(str).apply(clean_svg)

for i in range(3):
    print("=" * 100)
    print(train_df["svg_clean"].iloc[i][-500:])

"""Validate"""

valid_list = []
valid_reason_list = []

for i, svg in enumerate(train_df["svg_clean"]):
    if i % 5000 == 0:
        print(f"processing {i}/{len(train_df)}")
    val = validate_svg(svg)
    valid_list.append(val["valid"])
    valid_reason_list.append(val["reason"])

train_df["svg_valid"] = valid_list
train_df["svg_valid_reason"] = valid_reason_list

clean_train_df = train_df[train_df["svg_valid"] == True].copy()

print("Original:", len(train_df))
print("After validation:", len(clean_train_df))
print(train_df["svg_valid_reason"].value_counts().head(20))

"""Load tokenizer"""

MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("eos_token:", tokenizer.eos_token)
print("pad_token:", tokenizer.pad_token)

"""Reconnect tokenizer"""

MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"
adapter_dir = "/content/drive/MyDrive/svg_lora_clean_adapter"

tokenizer = AutoTokenizer.from_pretrained(adapter_dir, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

"""Create train"""

def format_svg_sample(prompt: str, svg_code: str):
    return f"Prompt: {prompt}\nSVG:\n{svg_code}"

clean_train_df["text"] = clean_train_df.apply(
    lambda row: format_svg_sample(row["prompt"], row["svg_clean"]),
    axis=1
)

print(clean_train_df["text"].iloc[0][:2000])

"""Calculate token size"""

clean_train_df["token_len"] = clean_train_df["text"].apply(
    lambda x: len(tokenizer(x, add_special_tokens=True)["input_ids"])
)

short_df = clean_train_df[clean_train_df["token_len"] <= 1536].copy()

print("Total cleaned:", len(clean_train_df))
print("Short training set <= 1536:", len(short_df))
print(short_df["token_len"].describe())

"""6000 samples split to train/test set"""

train_subset_df = short_df.sample(
    n=min(6000, len(short_df)),
    random_state=42
).copy()

dataset = Dataset.from_pandas(train_subset_df[["text"]])

split = dataset.train_test_split(test_size=0.02, seed=42)
train_dataset = split["train"]
val_dataset = split["test"]

print("train_dataset:", train_dataset)
print("val_dataset:", val_dataset)

"""Load 4 bit modle"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

model = prepare_model_for_kbit_training(model)

"""LoRA setup"""

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
)

model = get_peft_model(model, lora_config)
model.config.use_cache = False
model.print_trainable_parameters()

"""Train setup"""

MAX_SEQ_LENGTH = 1536

training_args = TrainingArguments(
    output_dir="/content/svg_lora_4b_run",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=2e-5,
    lr_scheduler_type="cosine",
    warmup_steps=20,
    logging_steps=20,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=2,
    bf16=True,
    fp16=False,
    gradient_checkpointing=True,
    optim="paged_adamw_8bit",
    max_grad_norm=0.3,
    report_to="none",
)

from google.colab import drive
drive.mount('/content/drive')

"""Train starter and saver"""

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
)

trainer.train()

model.save_pretrained("/content/svg_lora_clean_adapter")
save_dir = "/content/drive/MyDrive/svg_lora_clean_adapter"

model.save_pretrained(save_dir)
tokenizer.save_pretrained(save_dir)

print("Model saved")
!cp -r /content/drive/MyDrive/svg_lora_clean_adapter /content/

"""Change mod"""

model.gradient_checkpointing_disable()
model.config.use_cache = True
model.eval()

"""Torch.no_grad"""

@torch.no_grad()
def generate_svg(prompt, model, tokenizer, max_new_tokens=512):
    prefix = '<svg xmlns="http://www.w3.org/2000/svg" '
    text = f"Prompt: {prompt}\nSVG:\n{prefix}"
    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id,
        repetition_penalty=1.05,
    )

    input_len = inputs["input_ids"].shape[1]
    new_tokens = outputs[0][input_len:]
    continuation = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
    return prefix + continuation

def has_visible_shape(svg: str) -> bool:
    '''
    Check if the SVG has any visible shapes
    This is used to avoid  empty output
    '''
    visible_tags = ["<path", "<rect", "<circle", "<ellipse", "<line", "<polyline", "<polygon"]
    return any(tag in svg for tag in visible_tags)

def extract_first_svg(text: str) -> str:
    '''
    Extract the first valid svg block from the model output
    The model generate extra text, isolates the svg portion and apply debug
    '''
    text = strip_code_fences(text)
    text = remove_special_tokens(text)

    text = text.replace("<svgxmlns", "<svg xmlns")
    text = text.replace("<svgviewBox", "<svg viewBox")
    text = text.replace("<svgwidth", "<svg width")
    text = text.replace("<svgheight", "<svg height")
    text = text.replace('fill=""', 'fill="black"')
    text = text.replace("fill=''", "fill='black'")

    m = re.search(r"<svg[\s\S]*?</svg>", text)
    if m:
        return m.group(0).strip()

    m2 = re.search(r"<svg[\s\S]*", text)
    if m2:
        candidate = m2.group(0).strip()
        if "</svg>" not in candidate:
            candidate = candidate + "</svg>"
        return candidate

    return text.strip()

def repair_common_svg_issues(svg: str) -> str:
    '''
    Repair common structural issues in generated svg
    Fixes include:
    - Malformed <svg> tag
    - Extra whitespace
    - Empty fill attributes
    - Truncated closing tags (e.g., </pa, </pat)
    - Missing closing tags for <path>, <g>, or <svg>
    '''
    svg = svg.strip()

    svg = re.sub(r"<svgxmlns=", '<svg xmlns=', svg)
    svg = re.sub(r"<svg(?=(?:width|height|viewBox|xmlns)=)", "<svg ", svg)

    svg = re.sub(r"\s{2,}", " ", svg)

    svg = svg.replace('fill=""', 'fill="black"')
    svg = svg.replace("fill=''", "fill='black'")

    svg = re.sub(r"</p$", "", svg)
    svg = re.sub(r"</pa$", "", svg)
    svg = re.sub(r"</pat$", "", svg)
    svg = re.sub(r"</path$", "", svg)
    svg = re.sub(r"</g$", "", svg)
    svg = re.sub(r"</cl$", "", svg)
    svg = re.sub(r"</clipP.*$", "", svg)

    if "<path" in svg and "</path>" not in svg:
        svg += "</path>"

    if "<g" in svg and "</g>" not in svg:
        svg += "</g>"

    if svg.startswith("<svg") and "</svg>" not in svg:
        svg += "</svg>"

    return svg.strip()

def enforce_canvas(svg: str) -> str:
    '''
    Ensure SVG satisfies requirments
    - Extracts and repairs SVG
    - Enforces required attributes:
        - xmlns
        - width=256
        - height=256
        - viewBox="0 0 256 256"
    '''
    svg = extract_first_svg(svg)
    svg = repair_common_svg_issues(svg)

    if svg.startswith("<svg"):
        if 'xmlns=' not in svg:
            svg = svg.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"', 1)
        if 'width=' not in svg:
            svg = svg.replace("<svg", '<svg width="256"', 1)
        if 'height=' not in svg:
            svg = svg.replace("<svg", '<svg height="256"', 1)
        if 'viewBox=' not in svg:
            svg = svg.replace("<svg", '<svg viewBox="0 0 256 256"', 1)

    svg = svg.replace('fill=""', 'fill="black"')
    svg = svg.replace("fill=''", "fill='black'")
    return svg

def fallback_svg():
    '''
    Return a minimal valid SVG as fallback, used when all validation attempts fail.
    '''
    return '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256"><rect width="256" height="256" fill="white"/></svg>'

def sanitize_generated_svg(svg: str) -> str:
    '''
    Main function to process pipeline for generated svg
    '''
    svg = extract_first_svg(svg)

    # extract svg portion
    svg = re.sub(r">\s+<", "><", svg)
    svg = re.sub(r"\s{2,}", " ", svg).strip()
    # Normalize whitespace
    svg = svg.replace('fill=""', 'fill="black"')
    svg = svg.replace("fill=''", "fill='black'")
    svg = svg.replace('fill="#FFFFFF"', 'fill="#000000"')
    svg = svg.replace("fill='#FFFFFF'", "fill='#000000'")

    # Validate svg
    val = validate_svg(svg)
    if val["valid"] and has_visible_shape(svg):
        return svg

    svg_fixed = enforce_canvas(svg)
    svg_fixed = re.sub(r">\s+<", "><", svg_fixed)
    svg_fixed = re.sub(r"\s{2,}", " ", svg_fixed).strip()
    svg_fixed = svg_fixed.replace('fill=""', 'fill="black"')
    svg_fixed = svg_fixed.replace("fill=''", "fill='black'")
    svg_fixed = svg_fixed.replace('fill="#FFFFFF"', 'fill="#000000"')
    svg_fixed = svg_fixed.replace("fill='#FFFFFF'", "fill='#000000'")

    val2 = validate_svg(svg_fixed)

    if val2["valid"] and has_visible_shape(svg_fixed):
        return svg_fixed
    # fallback
    return fallback_svg()

def generate_best_svg(prompt, model, tokenizer, tries=1, max_new_tokens=512):
    '''
    Generate SVG with multiple attemptes and get the best one
    '''
    candidates = []

    for _ in range(tries):
        raw_svg = generate_svg(
            prompt,
            model,
            tokenizer,
            max_new_tokens=max_new_tokens
        )
        final_svg = sanitize_generated_svg(raw_svg)
        val = validate_svg(final_svg)

        shape_score = 1 if has_visible_shape(final_svg) else 0

        score = (
            shape_score,
            val["path_count"],
            len(final_svg)
        )
        candidates.append((score, final_svg))

    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]

"""Test result"""

from IPython.display import SVG, display

sample_prompts = short_df["prompt"].sample(10, random_state=42).tolist()

success = 0

for prompt in sample_prompts:
    print("=" * 100)
    print("PROMPT:", prompt)

    final_svg = generate_best_svg(prompt, model, tokenizer, tries=3)
    val = validate_svg(final_svg)

    print("\nFINAL SVG:")
    print(final_svg[:1200])
    print("\nVALIDATION FINAL:")
    print(val)
    print("Has visible shape:", has_visible_shape(final_svg))

    if val["valid"] and has_visible_shape(final_svg):
        success += 1

    try:
        display(SVG(final_svg))
    except Exception as e:
        print("Display failed:", e)

print(f"\nSuccessful non-empty SVGs: {success}/{len(sample_prompts)}")

"""Generate Submission file"""

import os
import pandas as pd

save_path = "/content/submission_partial.csv"

submission_rows = []

if os.path.exists(save_path):
    existing_df = pd.read_csv(save_path)
    submission_rows = existing_df.to_dict("records")
    done_ids = set(existing_df["id"])
    print(f"Resuming from {len(submission_rows)} samples")
else:
    done_ids = set()

tries = 1
max_new_tokens = 512

for i, row in test_df.iterrows():
    if row["id"] in done_ids:
        continue

    if i % 10 == 0:
        print(f"generating {i}/{len(test_df)}")

    pred_svg = generate_best_svg(
        prompt=row["prompt"],
        model=model,
        tokenizer=tokenizer,
        tries=tries,
        max_new_tokens=max_new_tokens
    )

    submission_rows.append({
        "id": row["id"],
        "svg": pred_svg
    })

    if len(submission_rows) % 10 == 0:
        pd.DataFrame(submission_rows).to_csv(save_path, index=False)
        print(f"Saved {len(submission_rows)} samples")

submission_df = pd.DataFrame(submission_rows)
submission_df.to_csv("/content/submission.csv", index=False)

print("Done!")
print(submission_df.shape)

"""Check output file"""

print(submission_df.shape)
print(submission_df.columns.tolist())
print(submission_df.isnull().sum())